# Generated by Django 4.0.2 on 2022-02-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_cart_product_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='deafaultImage', upload_to='profile/'),
        ),
    ]
